@startuml

title __FIELD's Class Diagram__\n

  namespace com.example.simple_chat {
    namespace field {
      class com.example.simple_chat.field.MessageType {
          {static} + getTypeInt()
          {static} + getTypeString()
      }
    }
  }
  

  namespace com.example.simple_chat {
    namespace field {
      class com.example.simple_chat.field.MessageType.I {
          {static} + CALCULATOR : int
          {static} + CALENDAR : int
          {static} + IMAGE : int
          {static} + MUSIC : int
          {static} + PLAN : int
          {static} + TEXT : int
          {static} + TIME : int
          {static} + UNKNOWN : int
      }
    }
  }
  

  namespace com.example.simple_chat {
    namespace field {
      class com.example.simple_chat.field.MessageType.S {
          {static} + CALCULATOR : String
          {static} + CALENDAR : String
          {static} + IMAGE : String
          {static} + MUSIC : String
          {static} + PLAN : String
          {static} + TEXT : String
          {static} + TIME : String
      }
    }
  }
  

  namespace com.example.simple_chat {
    namespace field {
      class com.example.simple_chat.field.RecordInfo {
          + args : HashMap<String, Object>
          + content : String
          + owner : String
          + provide : String
          + resource : String
          + type : String
          + RecordInfo()
          + RecordInfo()
      }
    }
  }
  

  com.example.simple_chat.field.MessageType +-down- com.example.simple_chat.field.MessageType.I
  com.example.simple_chat.field.MessageType +-down- com.example.simple_chat.field.MessageType.S


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
